### ISSUE TITLE
BUG: Lack of alert for entering letters in 'Your Price' section in 'Book Exhange Hub'

### ISSUE THREAD

**Issue by chhavx1618** [anuragverma108/SwapReads#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Users are able to enter letters and symbols in the 'Your Price' section in 'Book Exchange Hub' under the Literary Realms Section. Only numbers should be allowed in this section, as even the currency can be selected above. 

### Screenshots

![image](https://github.com/anuragverma108/SwapReads/assets/152146397/aeaff23f-5705-4a84-8ad5-2898524b51fc)

### Files

index.html

### Tasks

1. Add an alert to notify users that only numbers are allowed, or remove the ability of having letters/symbols typed in this section.
2. Test the alert for different inputs.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chhavx1618** [comment]
I want to work on this issue under GSSOC'24, kindly assign it to me and I will make the improvements.

**Comment by anuragverma108** [comment]
Assigned! @chhavx1618 
Make sure to attach before & after screenshots in your PR and include the issue number. 
Also, please star the repo before working on it. Happy open-source contributing!

**Comment by chhavx1618** [comment]
Thank you @anuragverma108! I'll make sure to get this done asap :)
